[[assets]]
id = "rw_mvp:sprite_tank_body"
kind = "image"
path = "assets/rusted_warfare/units/tanks/tank.png"
source = "units/tanks/tank.png"

[[assets]]
id = "rw_mvp:sprite_tank_turret"
kind = "image"
path = "assets/rusted_warfare/units/tanks/tank_turret.png"
source = "units/tanks/tank_turret.png"

[[assets]]
id = "rw_mvp:sprite_artillery_body"
kind = "image"
path = "assets/rusted_warfare/units/tanks/artillery.png"
source = "units/tanks/artillery.png"

[[assets]]
id = "rw_mvp:sprite_helicopter_body"
kind = "image"
path = "assets/rusted_warfare/units/helicopter/helicopter.png"
source = "units/helicopter/helicopter.png"

[[assets]]
id = "rw_mvp:sprite_helicopter_blades"
kind = "image"
path = "assets/rusted_warfare/units/helicopter/helicopter_blades.png"
source = "units/helicopter/helicopter_blades.png"

[[assets]]
id = "rw_mvp:sprite_factory_top"
kind = "image"
path = "assets/rusted_warfare/units/mech_factory/mechFactoryTop.png"
source = "units/mech_factory/mechFactoryTop.png"

[[assets]]
id = "rw_mvp:sprite_factory_bottom"
kind = "image"
path = "assets/rusted_warfare/units/mech_factory/mechFactoryBottom.png"
source = "units/mech_factory/mechFactoryBottom.png"

[[assets]]
id = "rw_mvp:sprite_extractor"
kind = "image"
path = "assets/rusted_warfare/units/extractor/extractor.png"
source = "units/extractor/extractor.png"

[[assets]]
id = "rw_mvp:sprite_turret_base"
kind = "image"
path = "assets/rusted_warfare/units/turrets/turret_base.png"
source = "units/turrets/turret_base.png"

[[assets]]
id = "rw_mvp:sprite_turret_top"
kind = "image"
path = "assets/rusted_warfare/units/turrets/turret_top.png"
source = "units/turrets/turret_top.png"

[[assets]]
id = "rw_mvp:sprite_combat_engineer"
kind = "image"
path = "assets/rusted_warfare/units/combat_engineer/base.png"
source = "units/combat_engineer/base.png"
