format_version = 1
package_id = "official_base_game"
package_version = "0.1.0"
schema_version = 1

[fingerprint]
algorithm = "sha256-content-v2"
hash = "6d7f6e35d5bd8415f636e7e90a763641a5248f1c0d6b909e582883a20bc5f614"
file_count = 6

[[resources]]
id = "official:credits"

[[units]]
id = "official:factory"

[[units]]
id = "official:tank"

[[maps]]
id = "official:dev_test_map"
