[[object_layers]]
id = "resources"
z_index = 5

[[object_layers.objects]]
id = "west_credits"
kind = "resource_node"
x = 120.0
y = 320.0
width = 60.0
height = 60.0

[object_layers.objects.properties]
resource = "simple_warfare:resource.credits"
amount = "6000"

[[object_layers.objects]]
id = "east_credits"
kind = "resource_node"
x = 840.0
y = 320.0
width = 60.0
height = 60.0

[object_layers.objects.properties]
resource = "simple_warfare:resource.credits"
amount = "6000"
